# .github/workflows/unittests.yml

name: Run Unit Tests

on:
  push:
    branches: [ main, preprocessing ]  # Specify the branches you want the tests to run on
  pull_request:
    branches: [ main, preprocessing ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Specify your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt